name: TimoCloudPaperIdentifier
version: '${project.version}'
main: net.juligames.core.addons.timocloudidentifier.paper.TimoCloudPaperIdentifier
api-version: 1.18
author: Ture Bentzin
depend:
  - PaperCore
  - TimoCloud